const adminEndpoint={
    login:'admin/login',
    logout:'admin/logout',
    addTeacher:'admin/addteacher',
    addStudent:'admin/addstudent',
    getTeachers:'admin/teacherslist',
    getStudents:'admin/studentslist',
    createBatch:'admin/createBatch',
    getBatchList:'admin/getBatchList',
    getStudentsByBatchId:'admin/getStudentsByBatchId',
    createCourse:'admin/createCourse',
    getCourseList:'admin/getCourseList',
    deleteTeacher:'admin/deleteTeacher',
    deleteStudent:'admin/deleteStudent',
    editStudent:'admin/editStudent',
    editTeacher:'admin/editTeacher',
    editBatch:'admin/editBatch',
    addMCQCompetition:'admin/addMCQCompetition',
    getMCQCompetition:'admin/getMCQCompetition',
    createAnnouncement:'admin/createAnnouncement',
    getAnnouncements:'admin/getAnnouncements',
}
export default adminEndpoint